# Camera parameters
camera:
    left:
        fov: 90
        x: 2.0
        y: -0.5
        z: 1.4
        pitch: 0
        roll: 0
        yaw: 0
        width: 800
        height: 600
    right:
        fov: 90
        x: 2.0
        y: 0.5
        z: 1.4
        pitch: 0
        roll: 0
        yaw: 0
        width: 800
        height: 600

# Carla Config
verbose: false
host: 127.0.0.1 # IP of the host server (default: 127.0.0.1)
tm_port: 8000
port: 2000
width: 1920
height: 600
loop: false
sync: true
town: Town01

# Traffic Config
number_of_vehicles: 30
number_of_walkers: 10
safe: false
filterv: vehicle.*
generationv: All
filterw: walker.pedestrian.*
generationw: '2'
rolename: hero
seedw: 0
car_lights_on: True

# Dataset Config
frames_per_episode: 500
n_episodes: 3
dataset_path: ../../../lbc/dd
behaviour: cautious
