# Camera parameters
camera:
    left:
        fov: 90
        x: 2.2
        y: -0.15
        z: 0.88
        pitch: 0
        roll: 0
        yaw: 0
        width: 384
        height: 160
    right:
        fov: 90
        x: 2.2
        y: 0.15
        z: 0.88
        pitch: 0
        roll: 0
        yaw: 0
        width: 384
        height: 160

# Carla Config
verbose: false
host: 127.0.0.1 # IP of the host server (default: 127.0.0.1)
tm_port: 8000
port: 2000
width: 1024
height: 320
loop: false
sync: true
town: Town01

# Traffic Config

number_of_vehicles: 100
number_of_walkers: 0
safe: false
filterv: vehicle.*
generationv: All
filterw: walker.pedestrian.*
generationw: '2'
rolename: hero
seedw: 0
car_lights_on: True

# Dataset Config
frames_per_episode: 1000
n_episodes: 800
dataset_path: /home/moonlab/Desktop/karthik/LearningByCheating/dataset_2
behaviour: normal
model_path: /home/moonlab/Documents/LearningByCheating/training/image_direct/model-160.th
